jobs:
  include:
    - &test
      stage: test
      git:
        submodules: false
      os: linux
      dist: xenial # required for Python >= 3.7 on Linux
      language: python
      python: "2.7" # this works for Linux but is ignored on macOS or Windows 
      env: PYTHON=2.7
      before_install:
        - pip install --upgrade --progress-bar off pip
      install:
        - python setup.py --quiet sdist
        - # rm -rf formula.egg-info # see  https://github.com/pypa/pip/issues/4621
        - pip install dist/*.tar.gz
      script:
        - python setup.py pytest -a '--verbose'
    - <<: *test
      language: python
      python: "3.4"
      env: PYTHON=3.4
      before_install:
        - pip install --upgrade --progress-bar off pip pytest==4.6
    - <<: *test
      language: python
      python: "3.5"
      env: PYTHON=3.5
    - <<: *test
      language: python
      python: "3.6"
      env: PYTHON=3.6
    - <<: *test
      language: python
      python: "3.7"
      env: PYTHON=3.7
    - <<: *test
      language: python
      python: "3.8"
      env: PYTHON=3.8
    - <<: *test
      name: "Python 3.x on Windows"
      env: PATH=/c/Python3x:/c/Python3x/Scripts:$PATH
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python3 -y --params '/InstallDir:C:\Python3x'
        - python -m pip install --upgrade --progress-bar off pip
      install:
        - python setup.py --quiet sdist
        - python -m pip install dist/*.tar.gz
      script:
        - python setup.py pytest -a '--verbose'
    - <<: *test
      name: "Python 2.7 on MacOS"
      git:
        submodules: false
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      env:
        - PYTHON=2.7
      before_install:
        - python -m pip install --upgrade --progress-bar off pip pytest==4.6
      install:
        - python setup.py --quiet sdist
        - python -m pip install dist/*.tar.gz
      script:
        - python setup.py pytest -a '--verbose'
    - <<: *test
      name: "Python 3.x on MacOS"
      git:
        submodules: false
      os: osx
      osx_image: xcode10.2
      language: shell
      env:
        - PYTHON=3.x
      before_install:
        - |
          brew update; brew install python3;
          python3 -m pip install --upgrade --progress-bar off pip
      install:
        - python3 setup.py --quiet sdist
        - python3 -m pip install dist/*.tar.gz
      script:
        - python3 setup.py pytest -a '--verbose'
    - <<: *test
      name: "lint"
      git:
        submodules: false
      os: linux
      dist: xenial
      language: python
      python: "3.7"
      env: PYTHON=3.7
      install:
        - pip install --progress-bar off black isort pytest pybind11 # pylint
      script:
        - black --check --diff .
        - isort --check-only --diff --recursive --project=formula
        #- touch __init__.py TODO: add pylint.
        #- pylint .
        #- rm __init__.py
