jobs:
  include:
    - &test
      stage: test
      git:
        submodules: false
      os: linux
      dist: xenial # required for Python >= 3.7 on Linux
      language: python
      python: "2.7" # this works for Linux but is ignored on macOS or Windows 
      env: PYTHON=2.7
      before_install:
        - pip install --upgrade --progress-bar off pip
      install:
        - python setup.py --quiet sdist
        - # rm -rf formula.egg-info # see  https://github.com/pypa/pip/issues/4621
        - pip install dist/*.tar.gz
      script:
        - python setup.py pytest -a "--verbose"
    - <<: *test
      language: python
      python: "3.4"
      env: PYTHON=3.4
    - <<: *test
      language: python
      python: "3.5"
      env: PYTHON=3.5
    - <<: *test
      language: python
      python: "3.6"
      env: PYTHON=3.6
    - <<: *test
      language: python
      python: "3.7"
      env: PYTHON=3.7
    # - <<: *test TODO: add CONDA
    #   language: shell
    #   python: null
    #   env: CONDA=2.7
    #   before_install:
    #     - OS=Linux-x86_64
    #     - wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda${CONDA:0:1}-latest-$OS.sh
    #     - bash miniconda.sh -b -p $HOME/miniconda
    #     - export PATH="$HOME/miniconda/bin:$PATH"
    #     - conda config --set always_yes yes --set changeps1 no
    #     - conda config --add channels conda-forge
    #     - conda update -q conda
    #     - conda install -q conda-build
    #     - conda create -q -n test-environment python=$CONDA
    #     - source activate test-environment
    #   install:
    #     - conda build conda.recipe
    #     - conda install --use-local formula
    #   script:
    #     - python setup.py pytest --verbose

    # - <<: *test
    #   language: shell
    #   python: null
    #   env: CONDA=3.6
    #   before_install:
    #     - OS=Linux-x86_64
    #     - wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda${CONDA:0:1}-latest-$OS.sh
    #     - bash miniconda.sh -b -p $HOME/miniconda
    #     - export PATH="$HOME/miniconda/bin:$PATH"
    #     - conda config --set always_yes yes --set changeps1 no
    #     - conda config --add channels conda-forge
    #     - conda update -q conda
    #     - conda install -q conda-build
    #     - conda create -q -n test-environment python=$CONDA
    #     - source activate test-environment
    #   install:
    #     - conda build conda.recipe
    #     - conda install --use-local formula
    #   script:
    #     - python setup.py pytest --verbose

    - <<: *test
      name: "Python 3.7 on Windows"
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python -y
        - python -m pip install --upgrade --progress-bar off pip
      install:
        - python setup.py --quiet sdist
        - python -m pip install dist/*.tar.gz
      script:
        - python setup.py pytest -a "--verbose"

    - stage: lint
      git:
        submodules: false
      os: linux
      dist: xenial
      language: python
      python: "3.7"
      install:
        - pip install --progress-bar off black isort pytest pybind11 # pylint
      script:
        - black --check --diff .
        - isort --check-only --diff --recursive --project=formula
        #- touch __init__.py TODO: add pylint.
        #- pylint .
        #- rm __init__.py

    # - stage: test-osx TODO: add osx
    #   os: osx
    #   osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
    #   language: shell       # 'language: python' is an error on Travis CI macOS
    #   git:
    #     submodules: false
    #   name: "Tests on macOs"
    #   env:
    #     - PYTHON=2.7
    #     - PYTHON=3.6
    #     - PYTHON=3.7
    #     - CONDA=2.7
    #     - CONDA=3.6
    #     - CONDA=3.7
    #   before_install:
    #     - |
    #       if [ -n "$PYTHON" ]; then
    #         if [ "${PYTHON:0:1}" = "3" ]; then
    #           brew update; brew install python3;
    #         fi
    #       elif [ -n "$CONDA" ]; then
    #         OS=MacOSX-x86_64
    #         wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda${CONDA:0:1}-latest-$OS.sh
    #         bash miniconda.sh -b -p $HOME/miniconda
    #         export PATH="$HOME/miniconda/bin:$PATH"
    #         conda config --set always_yes yes --set changeps1 no
    #         conda config --add channels conda-forge
    #         conda update -q conda
    #         conda install -q conda-build
    #         conda create -q -n test-environment python=$CONDA
    #         source activate test-environment
    #       fi
    #   install:
    #     - if [ -n "$PYTHON" ]; then python setup.py --quiet sdist; fi
    #     - # if [ -n "$PYTHON" ]; then rm -rf formula.egg-info; fi # https://github.com/pypa/pip/issues/4621 uncomment on the future
    #     - if [ -n "$PYTHON" ]; then python -m pip install dist/*.tar.gz; fi 
    #     - if [ -n "$CONDA" ]; then conda build conda.recipe; fi
    #     - if [ -n "$CONDA" ]; then conda install --use-local formula; fi
    #   script:
    #     - python setup.py pytest --verbose 