name: Test on windows (x86-x64)

on: [pull_request]

jobs:
  test:
    name: Test on python ${{ matrix.python }} ${{ matrix.os }} (${{ matrix.architecture }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-latest]
        architecture: [x86, x64]
        python: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "pypy-3.8", "pypy-3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: ${{ matrix.architecture }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel pytest
      - name: Display Python version
        run: |
          python -m pip --version
          python -c "import sys; print(sys.version)"
      - name: Build and install
        run: |
          python -m pip install --verbose --target formula-tmp .
      - name: Test
        run: |
          python -m pytest --verbose formula-tmp
